version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    env_file:
      - .env
    build:
      context: ../backend # backend 폴더를 build context로
      dockerfile: Dockerfile # ../backend/Dockerfile
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: backend
    restart: always
    ports:
      - "80:8000" # 도커 외부 80 → 내부 8000
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
